name: DevBuild

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: init
        run: |
          npm i -g pnpm
          pnpm install
      - name: update .gitignore
        run: sed -i -e '/\/dist/d' .gitignore
      - name: generate dev build
        run: pnpm build
      - name: setup sandbox
        run: |
          cp ./dist/niwango-core.js ./docs/
          cp ./src/parser/parser.js ./docs/
      - name: generate typedoc
        run: pnpm typedoc
      - name: update .gitignore
        run: sed -i -e '/\/docs\/type/d' .gitignore
      - name: Create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions@xpadev.net"
          git config user.name "github-actions"
          git checkout -b dev-build
          git add .
          git commit -m "auto generate" -n
          git push -f origin dev-build
