name: Typescript Jest

on:
  push:
    paths:
      - "src/**"

defaults:
  run:
    shell: bash

jobs:
  typescript-jest:
    name: Typescript Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run tests
        run: pnpm test
